### ISSUE TITLE
Feature request: specify client payload as path to json file

### ISSUE THREAD

**Issue by webignition** [peter-evans/repository-dispatch#105]
Specifying the `client-payload` value can be problematic. As this is created within a workflow file, I can't benefit from any syntax validation or syntax highlighting that might otherwise help in spotting a mistake.

If I were instead able to store the required payload in a file, I could:

 - use my IDE's syntax highlighting to make me aware of the mistakes my fallible human brain makes
 - lint json payload files in pull requests and fail builds if invalid json is encountered
 - make my workflow yaml easier to hand edit by not having to mentally switch between yaml and json modes in my head

Ideally a workflow step may then end up looking like:

```yaml
- name: Dispatch event
  uses: peter-evans/repository-dispatch@v1
  with:
    repository: example/repo
    event-type: event-type-name
    client-payload-file: ./path/to/payload.json
```

**Comment by peter-evans** [comment]
Hi @webignition 

It should be doable without needing to alter the action by reading the file in a previous workflow step. Actions are designed to be chained together like this for simplicity/modularity.

```yml
      - id: get-payload
        run: echo ::set-output name=payload::$(cat my-payload.json)

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: username/my-repo
          event-type: my-event
          client-payload: ${{ steps.get-payload.outputs.payload }}
```
