### ISSUE TITLE
Error: Parameter token or opts.auth is required

### ISSUE THREAD

**Issue by KIANSEONG** [peter-evans/repository-dispatch#117]
The workflow does not run. I am admin of the public repository.

**PRUpdates.yml** - Workflow that sends the dispatch.
```
name: PR Updates

on:
  pull_request:
    types: [opened, reopened]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    name: Trigger Telegram notifier workflow
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2.0.0
        with:
          token: ${{ secrets.PAT }}
          event-type: pr-opened
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "title": "${{ github.event.pull_request.title }}", "creator": "${{ github.actor }}"}'
```

**notifier.yml** - Workflow triggered on dispatch
```

name: GitHub Notifier

on:
  repository_dispatch:
    types: [pr-opened]

jobs:
  build:
    name: Telegram Notify
    runs-on: ubuntu-latest
    steps:
      - name: Notify telegram group on pull request changes
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }} # don't change
          token: ${{ secrets.TELEGRAM_TOKEN }} # don't change
          ref: ${{ github.event.client_payload.ref }}
          message: |
            **${{ github.event.client_payload.title }}**
            @${{ github.event.client_payload.creator }} opened a pull request.
```

<img width="827" alt="Screenshot 2022-10-04 at 10 37 13 AM" src="https://user-images.githubusercontent.com/53166471/193722775-e7d1dca6-ceb3-46c3-b98d-30038d00e738.png">

<img width="771" alt="Screenshot 2022-10-04 at 11 02 17 AM" src="https://user-images.githubusercontent.com/53166471/193725423-5caf6230-f4d7-47a4-87b1-4983def8672e.png">

**Token**
<img width="771" alt="Screenshot 2022-10-04 at 10 54 03 AM" src="https://user-images.githubusercontent.com/53166471/193724528-33899111-260f-4844-864c-047c60231df5.png">
