### ISSUE TITLE
Using yaml as client-payload

### ISSUE THREAD

**Issue by koenbeckers** [peter-evans/repository-dispatch#149]
Would it be possible, rather than specifying the client-payload as a json string, to juist build a yaml object and have that be converted into json?

```yaml
- name: Repository Dispatch
  uses: peter-evans/repository-dispatch@v2
  with:
    token: ${{ secrets.PAT }}
    repository: username/my-repo
    event-type: my-event
    client-payload:
      ref: ${{ github.ref }}
      sha: ${{ github.sha }}
      
```
