### ISSUE TITLE
Unexpected token ' in JSON at position 0 | Multiline client_payload

### ISSUE THREAD

**Issue by justmike1** [peter-evans/repository-dispatch#157]
So I am trying to implement a multiline client_payload, my configuration:

```yaml
  call-gke-cd:
    if: >
      ${{
      (startsWith(github.event.head_commit.message, '[PROD]:')) || 
      (github.ref != 'refs/heads/master')
      }}
    name: CD / Deploy to Kubernetes
    runs-on: ubuntu-22.04
    needs: [affected-services, build-and-push-docker]
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          repository: myorg/myrepo
          event-type: deploy
          client-payload: >
            '{"ref": "${{ github.ref }}", 
            "image_tag": "${{ needs.affected-services.outputs.project_version }}", 
            "services": "${{ needs.affected-services.outputs.matrix }}"}'
```

I get fails of `Unexpected token ' in JSON at position 0`

**Comment by peter-evans** [comment]
Hi @justmike1 

This site might help you:
https://yaml-multiline.info/

You probably want `>-`, but I'm not sure.
```yml
          client-payload: >-
            '{"ref": "${{ github.ref }}", 
            "image_tag": "${{ needs.affected-services.outputs.project_version }}", 
            "services": "${{ needs.affected-services.outputs.matrix }}"}'
```

Or it might be complaining about the quotes. Try removing them.
```yml
          client-payload: >-
            {"ref": "${{ github.ref }}", 
            "image_tag": "${{ needs.affected-services.outputs.project_version }}", 
            "services": "${{ needs.affected-services.outputs.matrix }}"}
```
