### ISSUE TITLE
Workflows not triggering when there are multiple repositories

### ISSUE THREAD

**Issue by neverkas** [peter-evans/repository-dispatch#184]
Hi, I'm trying to use an repository which receives the same event from different repositories. What I don't understand it's why it works with a repository (A) and it doesn't work if I've the same configuration in a repository (B).

This is my subtree repository on `listen-dispatch.yml`

```yaml
# listen-dispatch.yml file 
name: listen trigger events from another repository

on:
  repository_dispatch:
    types: [update-subtree-repository]

jobs:
  build:
    name: run-workflow
    runs-on: self-hosted
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
      - name: Create environment variables
        run: |
          echo "REPOSITORY_NAME=`basename ${{ github.event.client_payload.repository }}`" >> $GITHUB_ENV
          echo "REPOSITORY_URL=git@github.com:${{ github.event.client_payload.repository }}.git" >> $GITHUB_ENV
      - name: Get changes
        run: make git-subtree-pull REPOSITORY_NAME=${{ env.REPOSITORY_NAME}} REPOSITORY_URL=${{ env.REPOSITORY_URL }}
      - name: update changes
        run: make upload-changes-to-remote
```

This is what I've on my repositories which send the event to the previous one, there's one of them which works though there is another one which has the same configuration and share the access token from the same organization, both are private repositories.

```yml
# repository-dispatch.yml file on multiple repositories from the same organization which share the same PAT
name: trigger events in another repository

on:
  push:
    branches: [ master ]

jobs:
  testing-trigger:
    runs-on: self-hosted
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2.1.1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: myorg/mysubtree-repo
          event-type: update-subtree-repository
          client-payload: '{ "repository": "${{ github.repository }}" }' # optional, default is {}
```
