### ISSUE TITLE
Hot To Get Json From Sender to Receiver

### ISSUE THREAD

**Issue by nurirppan** [peter-evans/repository-dispatch#190]
i am using this code from a.yml (sender)

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        if: always()
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: abc/cde
          event-type: cd_development_event
          client-payload: >-
            {
                "sha": "${{ github.sha }}",
                "ref": "${{ github.ref }}",
                "configuration": "${{ github.event.inputs.configuration }}",
                "deployment": "${{ github.event.inputs.deployment }}",
                "note": "${{ github.event.inputs.note }}",
                "webhook": "${{ secrets.WEBHOOK_TEAMS_DEVELOPMENT }}",
                "needs": ${{ toJson(needs) }},
                "job": ${{ toJson(job) }},
                "steps": ${{ toJson(steps) }}
            }

and for receiver in b.yml, iam using like this
      - name: Send a Report
        uses: skitionek/notify-microsoft-teams@master
        with:
          needs: ${{ github.event.client_payload.needs }}
          job: ${{ github.event.client_payload.job }}
          steps: ${{ github.event.client_payload.steps }}

and when send a report is run, i got an error. this is my error :
Error: .github/workflows/cn_teams.yml (Line: 47, Col: 18): A mapping was not expected
Error: .github/workflows/cn_teams.yml (Line: 48, Col: 16): A mapping was not expected
Error: .github/workflows/cn_teams.yml (Line: 49, Col: 18): A mapping was not expected
Error: The template is not valid. .github/workflows/cn_teams.yml (Line: [4](abc/cde/actions/runs/4541842895/jobs/8004521771#step:6:4)7, Col: 18): A mapping was not expected,.github/workflows/cn_teams.yml (Line: 48, Col: 16): A mapping was not expected,.github/workflows/cn_teams.yml (Line: 49, Col: 18): A mapping was not expected

and when i am display value from reciver, this my error
      # - name: needs  
      #   run: echo ${{ github.event.client_payload.needs }}

output : {}

      # - name: job  
      #   run: echo ${{ github.event.client_payload.job }}

output : {}

expected output :
{
    "needs": {},
    "job": {
        "status": "success"
    },
    "steps": {}
}

please, how to get that json from sender to receiver. thank you

**Comment by peter-evans** [comment]
Hi @nurirppan 

It's a bit difficult to understand what you are trying to do here, but perhaps you need `fromJson` like this:

```yml
needs: ${{ fromJson(github.event.client_payload.needs) }}
job: ${{ fromJson(github.event.client_payload.job) }}
steps: ${{ fromJson(github.event.client_payload.steps) }}
```

I don't know, though. This is just a guess.

**Comment by nurirppan** [comment]
> Hi @nurirppan
> 
> It's a bit difficult to understand what you are trying to do here, but perhaps you need `fromJson` like this:
> 
> ```yaml
> needs: ${{ fromJson(github.event.client_payload.needs) }}
> job: ${{ fromJson(github.event.client_payload.job) }}
> steps: ${{ fromJson(github.event.client_payload.steps) }}
> ```
> 
> I don't know, though. This is just a guess.

hello sir, i got this error 
Error: .github/workflows/cn_teams.yml (Line: 44, Col: 18):
Error: .github/workflows/cn_teams.yml (Line: 45, Col: 16):
Error: .github/workflows/cn_teams.yml (Line: 46, Col: 18):
Error: The template is not valid. .github/workflows/cn_teams.yml (Line: [4](https://github.com/pt-kompas-media-nusantara/kompas-id-ios-v2/actions/runs/4549623498/jobs/8021868893#step:6:4)4, Col: 18): Unexpected character encountered while parsing value: O. Path '', line 0, position 0.,.github/workflows/cn_teams.yml (Line: 45, Col: 16): Unexpected character encountered while parsing value: O. Path '', line 0, position 0.,.github/workflows/cn_teams.yml (Line: 46, Col: 18): Unexpected character encountered while parsing value: O. Path '', line 0, position 0.

i implent like this 
a.yml
```
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        if: always()
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: abc/def
          event-type: cd_development_event
          client-payload: >-
            {
                "sha": "${{ github.sha }}",
                "ref": "${{ github.ref }}",
                "configuration": "${{ github.event.inputs.configuration }}",
                "deployment": "${{ github.event.inputs.deployment }}",
                "note": "${{ github.event.inputs.note }}",
                "webhook": "${{ secrets.WEBHOOK_TEAMS_DEVELOPMENT }}",
                "needs": ${{ toJson(needs) }},
                "job": ${{ toJson(job) }},
                "steps": ${{ toJson(steps) }}
            }
```
            
            
```
b.yml
      - name: Send a Report
        uses: skitionek/notify-microsoft-teams@master
        with:
          webhook_url: ${{ github.event.client_payload.webhook }}
          needs: ${{ fromJson(github.event.client_payload.needs) }}
          job: ${{ fromJson(github.event.client_payload.job) }}
          steps: ${{ fromJson(github.event.client_payload.steps) }}
          # needs: ${{ toJson(needs) }} # ${{ github.event.client_payload.needs }}
          # job: ${{ toJson(job) }} # ${{ github.event.client_payload.job }}
          # steps: ${{ toJson(steps) }} # ${{ github.event.client_payload.steps }}
          # needs: ${{ github.event.client_payload.needs }}
          # job: ${{ github.event.client_payload.job }}
          # steps: ${{ github.event.client_payload.steps }}
```
