### ISSUE TITLE
Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by jypucca** [peter-evans/repository-dispatch#196]
Hi, thank you for this repo! I'm trying to apply `repository_dispatch` in the same repo and pass metadata from one workflow to another. My code is shown below and it's throwing an error `Error: Resource not accessible by integration`. Why is it throwing that error? I thought for local dispatch it doesn't need `secrets.GITHUB_TOKEN` or PAT?

```
  save-to-dispatch:
    runs-on: ubuntu-latest
    needs: [set-tag, build-image-and-push]
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: version-tag
          client-payload: '{"dispatch_origin": "production", "tag": "${{ needs.set-tag.outputs.tag }}"}'
```

**Comment by jypucca** [comment]
I figured it out. It worked after I changed the workflow permission to `contents: write`.

**Comment by erichstuder** [comment]
May I suggest to add this hint to the example in the [README.md](https://github.com/peter-evans/repository-dispatch/blob/main/README.md)? I had the same problem and found the same solution. Would be nice to have a hint about that.


Dispatch an event to the current repository.
```yml
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: my-event
```
