### ISSUE TITLE
Deprecated warning when using latest version

### ISSUE THREAD

**Issue by Eneuman** [peter-evans/repository-dispatch#240]
When using the latest version you now get the following warning:

`The following actions uses node12 which is deprecated and will be forced to run on node16: peter-evans/repository-dispatch@v1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/`

**Comment by peter-evans** [comment]
Hi @Eneuman 

The latest version is `v2`. Please check the readme.

```yml
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: my-event
```
