### ISSUE TITLE
Multiple event-type values in the receiving job?

### ISSUE THREAD

**Issue by pradeipp** [peter-evans/repository-dispatch#273]
We have a dev repo from which we want to trigger jobs in e2e test repository. We have multiple environments and with the github actions plan we've come up with we have a separate step for each environment. Each step sends a repository_dispatch trigger. That will total in about 7 triggers per step/environment. 
```yaml
- name: Trigger e2e-test-ch-prod
  uses: peter-evans/repository-dispatch@v2
  with:
    token: ${{ secrets.PAT }}
    repository: my-shop/e2e-tests
    event-type: test-us-prod
    client-payload: '{"ENV": "prod", "LOCALE": "US"}'

- name: Trigger e2e-test-uk-prod
  uses: peter-evans/repository-dispatch@v2
  with:
    token: ${{ secrets.PAT }}
    repository: my-shop/e2e-tests
    event-type: test-uk-prod
    client-payload: '{"ENV": "prod", "LOCALE": "UK"}'
```

The receiving e2e test repository will have one workflow for simple e2e tests. In the 'on' section, in the 'types' field, can we use a list like 

```
on:
  repository_dispatch:
    types: ['test-us-prod', 'test-us-staging', 'test-uk-prod', 'test-uk-staging']
```

will this work?
