### ISSUE TITLE
Dispatch same event to several repos

### ISSUE THREAD

**Issue by Enchufa2** [peter-evans/repository-dispatch#29]
Is this possible without duplicating the step several times? Something like

```yaml
- name: Repository Dispatch
  uses: peter-evans/repository-dispatch@v1
  with:
    token: ${{ secrets.REPO_ACCESS_TOKEN }}
    repository: [slug1/repo1, slug2/repo2, ...]
    event-type: my-event
```

**Comment by peter-evans** [comment]
Hi @Enchufa2 

I *could* add this functionality to the action, but I think I would prefer not to add it and keep the action super-simple. How about using the matrix feature of jobs in GitHub Actions instead? Does this work for you?

```
  dispatch:
    strategy:
      matrix:
        repo: ['slug1/repo1', 'slug2/repo2']
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: my-event
```
