### ISSUE TITLE
[error] Resource not accessible by integration

### ISSUE THREAD

**Issue by MrThanlon** [peter-evans/repository-dispatch#33]
```yml
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1.1.1
      with:
        # A repo scoped GitHub Personal Access Token
        token: ${{ secrets.GITHUB_TOKEN }}
        # The full name of the repository to send the dispatch.
        repository: MrThanlon/meclass
        # A custom webhook event name.
        event-type: updated
```
