### ISSUE TITLE
[FEATURE REQUEST] Send multiple events at once

### ISSUE THREAD

**Issue by Badisi** [peter-evans/repository-dispatch#331]
Thanks for this GH action !

I was wondering if it would be possible to send multiple events at once ?

I'm currently reusing too many workflows and hitting the error "too many workflows are referenced, total: 22, limit: 20".
See the [documentation](https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations).
So it would be great to only use your workflow once and send all my events, instead of using a job per event.

**Comment by gnpaone** [comment]
Yeah, I need this too.

**Comment by peter-evans** [comment]
Please could you explain your problem in more detail, preferably with examples. My current recommendation is to use a matrix, [as described in the readme](https://github.com/peter-evans/repository-dispatch#dispatch-to-multiple-repositories). Could you explain why that doesn't work for your use case(s).

**Comment by gnpaone** [comment]
For example if we use the matrix, the same workflow runs twice (duplicate run for other steps) instead dispatch I want to dispatch to multiple repos or multiple events in single step

Example:
```yaml
- name: Repo dispatch
  uses: peter-evans/repository-dispatch@v3
  with:
    event-type: ${{ matrix.events }}
```

![Image](https://github.com/user-attachments/assets/32a1a4d5-a5f5-479f-afbb-350ffb81fbe1)

**Comment by Badisi** [comment]
My personal use case is to dispatch multiple events in a row, not to dispatch an event to multiple repos.

The goal is to use your workflow once instead of N times, and do not break the total limit.

#### Example

Do this:
```yaml
jobs:
    ci_tests:
        runs-on: 'ubuntu-latest'
        steps:
            - name: Test component A, B, C
              uses: peter-evans/repository-dispatch@v3
              with:
                  event-types: [test_compA, test_compB, test_compC]
```

instead of this:
```yaml
jobs:
    ci_tests:
        runs-on: 'ubuntu-latest'
        steps:
            - name: Test component A
              uses: peter-evans/repository-dispatch@v3
              with:
                  event-type: test_compA

            - name: Test component B
              uses: peter-evans/repository-dispatch@v3
              with:
                  event-type: test_compB

            - name: Test component C
              uses: peter-evans/repository-dispatch@v3
              with:
                  event-type: test_compC
```

**Comment by gnpaone** [comment]
@Badisi Exactly the same use case for me too. By using matrix it's same as

```yaml
jobs:
    ci_tests:
        runs-on: 'ubuntu-latest'
        steps:
            - name: Test component A
              uses: peter-evans/repository-dispatch@v3
              with:
                  event-type: test_compA

            - name: Test component B
              uses: peter-evans/repository-dispatch@v3
              with:
                  event-type: test_compB

            - name: Test component C
              uses: peter-evans/repository-dispatch@v3
              with:
                  event-type: test_compC
```

**Comment by gnpaone** [comment]
Or it can be

```yaml
jobs:
    ci_tests:
        runs-on: 'ubuntu-latest'
        steps:
            - name: Test component A, B, C
              uses: peter-evans/repository-dispatch@v3
              with:
                  event-types: test_compA, test_compB, test_compC
```
