### ISSUE TITLE
Trigger workflow from outside of another repository

### ISSUE THREAD

**Issue by bschmitz9** [peter-evans/repository-dispatch#38]
Is there an event to listen for when something is pushed to an outside repository within my organization? 

I am trying to build a workflow that pushes a tag to a repository anytime a new repository is created and pushed to. I don't know when the repository will be created or who will create it. And I need to execute the workflow I have from outside of the repository I want to add the tag to. Is this possible?
```
name: Check Github Tags

on: push

jobs: 
  check-git-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Print Repository info
        run: |
          echo 'Commit:' $GITHUB_SHA
          echo 'Repository:' $GITHUB_REPOSITORY
          echo 'Workspace:' $GITHUB_WORKSPACE
          echo 'Ref:' $GITHUB_REF
          git tag
      - name: Push new tag
        id: push_new_tag
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: test2
      - name: Print New Tag Added
        run: echo 'New tag' ${{steps.push_new_tag.outputs.new_tag}} 'added to commit' $GITHUB_SHA 'in' $GITHUB_REPOSITORY.
```
