### ISSUE TITLE
Workflow runs regardless of event-type

### ISSUE THREAD

**Issue by truestblue** [peter-evans/repository-dispatch#65]
I have a test repo-dispatch action in my first repo:
```

name: Test 
on: 
  push:
    paths:
    - '.github/workflows/test-repo-dispatch.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{secrets.SECRET}}
          repository: polyverse/polyscripted-wordpress
          event-type: x
```

In my downstream repo it is supposed to run on a specific type of dispatch, yet is triggered regardless of what event type is added.
 
```
  repository_dispatch:    
    type: [build_7.2_apache]
```

The above workflow runs even with event type "x" sent.
