### ISSUE TITLE
Not triggering workflow

### ISSUE THREAD

**Issue by CWSites** [peter-evans/repository-dispatch#67]
Both of my workflows are on `master` of my repository. I'm not getting any error messages, however the workflow is not being triggered

## Workflow that should be the trigger
```yml
  verification:
    name: Workflow - Lint, Test & Build
    runs-on: 'ubuntu-latest'

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          event-type: run-lint-test-build
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
```

## Workflow that I am attempting to trigger
```yml
name: Lint, Test & Build

on:
  repository_dispatch:
    types: [run-lint-test-build]

jobs:
  verification:
    name: Lint, Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}
```

**Comment by peter-evans** [comment]
Hi @CWSites 

The default repository token does not work. You need to create a `repo` scoped PAT. Please see the note in the readme here: https://github.com/peter-evans/repository-dispatch#token

**Comment by CWSites** [comment]
Thanks for the info, I had read through all of that before and thought the token I was already using had the correct permissions. I got it working thanks to your comment.

It would be helpful if there was some kind of warning if the permissions aren't correct.

**Comment by peter-evans** [comment]
Glad you've got it working. 

Unfortunately I don't think there is any way to know that the permissions of the token are incorrect. The GitHub API this action calls does not return an error message. It might be deliberate for security reasons.

**Comment by rogerluan** [comment]
Hey 👋 

I'm facing the exact same issue as OP, 4 years later and I don't think a PAT is really needed, is it? The docs say:

https://github.com/peter-evans/repository-dispatch/blob/25b98225d848ef84c218faf938c2e9a7636de1f3/README.md?plain=1#L36-L39

For reference, here's my caller workflow:

```yaml
# … rest of the file

- name: Trigger infra deployment
  uses: peter-evans/repository-dispatch@v3
  with:
    event-type: deploy
    client-payload: >
      {
        "environment": "${{ env.ENVIRONMENT }}"
      }
```

And the callee:

```yaml
on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [deploy]
```

And what I'm getting is: the action isn't throwing any errors, but the workflow isn't triggered.

Thanks in advance for the help! 🙇‍♂
