### ISSUE TITLE
Repository not found, OR token has insufficient permissions.

### ISSUE THREAD

**Issue by jonfasking** [peter-evans/repository-dispatch#68]
What I've got:

 - Private organization where private repo A is attempting to trigger a dispatch to another private rebo B, in the same org
 - PAC being used is for a user that has Admin across the whole private org
 - PAC being used has god rights (everything is checked)

The workflow step:
```
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REDACTED_SECRET_NAME }}
          repository: redacted-org/redacted-repo
          event-type: redacted-event-name
          client-payload: '{"repo": "${{ github.repository }}", "release_id": "${{ steps.create_release.outputs.id }}", "chart_name": "${{ env.HELM_CHART_NAME }}"}'
```

The repository is defined as org-name/repo-name, and is spelled correctly.

The error:

> Error: Repository not found, OR token has insufficient permissions.

At this point, there is no higher permissions to give on either the user (which is part of the private org), or the PAC used in the workflow. Not sure what else to check. Thoughts?
