### ISSUE TITLE
is readme example correct?

### ISSUE THREAD

**Issue by UziTech** [peter-evans/repository-dispatch#7]
According to the [documentation](https://help.github.com/en/actions/reference/events-that-trigger-workflows#external-events-repository_dispatch) the `repository_dispatch` event doesn't use the `types` property.

> This event does not have additional activity types so it does not support the `types` keyword.

Should the example be:

```yml
name: Repository Dispatch
on: repository_dispatch

jobs:
  myEvent:
    if: github.event.action == 'my-event'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}
```

or does it work with the `types` property?
