### ISSUE TITLE
Specify what branch to trigger on remote repo

### ISSUE THREAD

**Issue by paolocloudmade** [peter-evans/repository-dispatch#70]
I have this job below on workflow one which will supposedly trigger another workflow which resides on the master branch on another repo.

This workflow is being triggered everytime a push event is captured on 'develop' branch
```
name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: same-user/another-repo
        event-type: trigger-deployment
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
```
It's triggering just fine but it's failing to run because workflow2 is looking for develop branch on my other repo which is not existent.

Is there a way to tell what branch is going to be triggered?
