### ISSUE TITLE
Is it possible to get the run_id that's triggered by repository-dispatch?

### ISSUE THREAD

**Issue by liya2017** [peter-evans/repository-dispatch#78]
Hi, I have a request like below:
1. trigger the do-something by repository-dispatch
2. need the do-something run id
3. check the do-something  status.
4. repeat above again and again

below is my yaml

```
  Benchmarks_Test:
    name: Build Modified
    runs-on: [ self-hosted, Linux, X64, package-for-linux ]
    strategy:
      matrix:
        repeat: [1, 2]
    continue-on-error: true
    concurrency:
      group: Benchmarks_Test_${{matrix.repeat}}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          event-type: do-something
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
      - name: check each  do-something status by run id
```
