### ISSUE TITLE
It is not triggering the workflow in other repo

### ISSUE THREAD

**Issue by eebasadre20** [peter-evans/repository-dispatch#88]
Both workflows are in default branch on each repos still not dispatching an event.

**Dispatcher**
```
name: Codegen
on:
  push:
    branches:
      - develop
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: org-name/repo-name
          event-type: my-event
```

**Reciever**
```

name: Graphql Codegen
on:
  repository_dispatch:
    types: [my-event]
jobs:
  codegen:
    runs-on: ubuntu-latest
    steps:
```

But when I tried to dispatch via curl, it triggers the workflow on the receiver repo.
```

   curl \
    -X POST \
    -H "Accept: application/vnd.github.v3+json" \
    -H "Authorization: token ghp_token_with_repo_workflow_scope" \
    https://api.github.com/repos/org-name/repo-name/dispatches \
    -d '{"event_type":"my-event","client_payload":{"command":"ping"}'
```

My personal access token has repo + worfklow scope
