### ISSUE TITLE
example property names don't align

### ISSUE THREAD

**Issue by markgoho** [peter-evans/repository-dispatch#89]
in the example, `client-payload` is kebab-case
``` yml
with:
  client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
```

but in the receiving repository's workflow, this property is referenced in snake_case:
``` yml
  with:
    ref: ${{ github.event.client_payload.ref }}
- run: echo ${{ github.event.client_payload.sha }}
```

I can see in the source what's happening - you've decided expect an input of `client-payload` but GitHub's API requires it be `client_payload` when sending this data through its API.

If this were to change it would be a breaking change and users would need to upgrade to a next major version of the action.
